image: ghcr.io/dwmorley/lancs-leeg-ossa:latest

tasks:
  - init: echo "App starting..."
    command: shiny run app.py --host 0.0.0.0 --port 8080

ports:
  - port: 8080
    onOpen: open-browser

env:
  R_HOME: /usr/lib/R
