"""Project-level constants and option mappings used by OSSA."""

URLS = {
    "lms": "https://www.lancaster.ac.uk/lms/",
    "leeg": "https://luigisedda.wordpress.com/",
    "github": "https://github.com/dwmorley/lancs-leeg-ossa",
    "luigi_email": "mailto:l.sedda@lancaster.ac.uk",
}

GRID_SAMPLE_SIZE = 500

START_DATE = "2019-01-01"
END_DATE = "2019-12-31"

RESPONSE_OPTIONS = {
    "io_landcoverio": "Impact Observatory Land Cover",
    "esa_ccilc": "ESA CCI Land Cover",
    "ecmwf_soil_type": "ERA5 Soil type (categorical)",
    "ecmwf_type_of_high_vegetation": "ERA5 Type of high vegetation (categorical)",
    "ecmwf_type_of_low_vegetation": "ERA5 Type of low vegetation (categorical)",
}

COVARIATE_OPTIONS = {
    "cop_dem_30": "Copernicus Digital Elevation Model (30m)",
    "cop_dem_90": "Copernicus Digital Elevation Model (90m)",
    "wp_1km_unadj": "World Pop Population 1km Unadjusted",
    "wp_1km": "World Pop Population 1km",
    "grip_0_all": "GRIP Road Density - All",
    "grip_1_highway": "GRIP Road Density - Highways",
    "grip_2_primary": "GRIP Road Density - Primary Roads",
    "grip_3_secondary": "GRIP Road Density - Secondary Roads",
    "grip_4_tertiary": "GRIP Road Density - Tertiary Roads",
    "grip_5_local": "GRIP Road Density - Local Roads",
    "modis_ET_500m": "MODIS Net Evapotranspiration (500m)",
    "modis_LE_500m": "MODIS Latent Heat Flux (500m)",
    "modis_PET_500m": "MODIS Potential Evapotranspiration (500m)",
    "modis_PLE_500m": "MODIS Potential Latent Heat Flux (500m)",
    "modis_LST_Day_1KM": "MODIS LST Day 8-Day (1km)",
    "modis_LST_Night_1KM": "MODIS LST Night 8-Day (1km)",
    "modis_LST_Day_1km": "MODIS LST Day Daily (1km)",
    "modis_LST_Night_1km": "MODIS LST Night Daily (1km)",
    "modis_Emis_31": "MODIS Band 31 Emissivity",
    "modis_Emis_32": "MODIS Band 32 Emissivity",
    "modis_Emis_29": "MODIS Band 29 Emissivity",
    "modis_Gpp_500m": "MODIS Gross Primary Productivity (500m)",
    "modis_PsnNet_500m": "MODIS Net Photosynthesis (500m)",
    "modis_Npp_500m": "MODIS Net Primary Production Yearly (500m)",
    "modis_sur_refl_b01": "MODIS Surface Reflectance Band 1 - Red (500m)",
    "modis_sur_refl_b02": "MODIS Surface Reflectance Band 2 - NIR (500m)",
    "modis_sur_refl_b03": "MODIS Surface Reflectance Band 3 - Blue (500m)",
    "modis_sur_refl_b04": "MODIS Surface Reflectance Band 4 - Green (500m)",
    "modis_sur_refl_b05": "MODIS Surface Reflectance Band 5 - SWIR (500m)",
    "modis_sur_refl_b06": "MODIS Surface Reflectance Band 6 - SWIR (500m)",
    "modis_sur_refl_b07": "MODIS Surface Reflectance Band 7 - SWIR (500m)",
    "modis_Nadir_Reflectance_Band1": "MODIS NBAR Band 1 - Red",
    "modis_Nadir_Reflectance_Band2": "MODIS NBAR Band 2 - NIR",
    "modis_Nadir_Reflectance_Band3": "MODIS NBAR Band 3 - Blue",
    "modis_Nadir_Reflectance_Band4": "MODIS NBAR Band 4 - Green",
    "modis_Nadir_Reflectance_Band5": "MODIS NBAR Band 5 - SWIR",
    "modis_Nadir_Reflectance_Band6": "MODIS NBAR Band 6 - SWIR",
    "modis_Nadir_Reflectance_Band7": "MODIS NBAR Band 7 - SWIR",
    "modis_250m_16_days_NDVI": "MODIS NDVI 16-Day (250m)",
    "modis_250m_16_days_EVI": "MODIS EVI 16-Day (250m)",
    "modis_250m_16_days_NIR_reflectance": "MODIS NIR Reflectance 16-Day (250m)",
    "modis_250m_16_days_MIR_reflectance": "MODIS MIR Reflectance 16-Day (250m)",
    "modis_250m_16_days_red_reflectance": "MODIS Red Reflectance 16-Day (250m)",
    "modis_250m_16_days_blue_reflectance": "MODIS Blue Reflectance 16-Day (250m)",
    "modis_500m_16_days_NDVI": "MODIS NDVI 16-Day (500m)",
    "modis_500m_16_days_EVI": "MODIS EVI 16-Day (500m)",
    "modis_500m_16_days_NIR_reflectance": "MODIS NIR Reflectance 16-Day (500m)",
    "modis_500m_16_days_MIR_reflectance": "MODIS MIR Reflectance 16-Day (500m)",
    "modis_500m_16_days_red_reflectance": "MODIS Red Reflectance 16-Day (500m)",
    "modis_500m_16_days_blue_reflectance": "MODIS Blue Reflectance 16-Day (500m)",
    "modis_Lai_500m": "MODIS Leaf Area Index (500m)",
    "modis_Fpar_500m": "MODIS Fraction of Photosynthetically Active Radiation (500m)",
    "modis_NDSI_Snow_Cover": "MODIS NDSI Snow Cover",
    "modis_Snow_Albedo_Daily_Tile": "MODIS Snow Albedo Daily",
    "modis_Maximum_Snow_Extent": "MODIS Maximum Snow Extent 8-Day",
    "modis_Eight_Day_Snow_Cover": "MODIS Eight Day Snow Cover",
    "modis_NDSI": "MODIS Normalised Difference Snow Index",
    "terraclimate_aet": "TerraClimate Actual Evapotranspiration",
    "terraclimate_def": "TerraClimate Water Deficit",
    "terraclimate_pet": "TerraClimate Potential Evapotranspiration",
    "terraclimate_ppt": "TerraClimate Precipitation",
    "terraclimate_q": "TerraClimate Runoff",
    "terraclimate_soil": "TerraClimate Soil Moisture",
    "terraclimate_srad": "TerraClimate Shortwave Radiation",
    "terraclimate_swe": "TerraClimate Snow Water Equivalent",
    "terraclimate_tmax": "TerraClimate Max Temperature",
    "terraclimate_tmin": "TerraClimate Min Temperature",
    "terraclimate_vap": "TerraClimate Vapor Pressure",
    "terraclimate_vpd": "TerraClimate Vapor Pressure Deficit",
    "terraclimate_ws": "TerraClimate Wind Speed",
    "terraclimate_pdsi": "TerraClimate Palmer Drought Severity Index",
    "ecmwf_2m_dewpoint_temperature": "ERA5 Dew point temperature at 2 meters above the surface (K)",
    "ecmwf_2m_temperature": "ERA5 Air temperature at 2 meters above the surface (K)",
    "ecmwf_skin_temperature": "ERA5 Temperature of the land surface (K)",
    "ecmwf_soil_temperature_level_1": "ERA5 Soil temperature at level 1 (K)",
    "ecmwf_soil_temperature_level_2": "ERA5 Soil temperature at level 2 (K)",
    "ecmwf_soil_temperature_level_3": "ERA5 Soil temperature at level 3 (K)",
    "ecmwf_soil_temperature_level_4": "ERA5 Soil temperature at level 4 (K)",
    # "ecmwf_lake_bottom_temperature": "ERA5 Lake bottom temperature (K)",
    # "ecmwf_lake_ice_depth": "ERA5 Lake ice depth (m)",
    # "ecmwf_lake_ice_temperature": "ERA5 Lake ice temperature (K)",
    # "ecmwf_lake_mix_layer_depth": "ERA5 Lake mix layer depth (m)",
    # "ecmwf_lake_mix_layer_temperature": "ERA5 Lake mix layer temperature (K)",
    # "ecmwf_lake_shape_factor": "ERA5 Lake shape factor (dimensionless)",
    # "ecmwf_lake_total_layer_temperature": "ERA5 Lake total layer temperature (K)",
    "ecmwf_snow_albedo": "ERA5 Snow albedo (dimensionless)",
    "ecmwf_snow_cover": "ERA5 Snow cover (fraction)",
    "ecmwf_snow_density": "ERA5 Snow density (kg m-3)",
    "ecmwf_snow_depth": "ERA5 Snow depth (m)",
    "ecmwf_snow_depth_water_equivalent": "ERA5 Snow depth water equivalent (kg m-2)",
    "ecmwf_snowfall": "ERA5 Snowfall (m)",
    "ecmwf_snowmelt": "ERA5 Snowmelt (m)",
    "ecmwf_temperature_of_snow_layer": "ERA5 Temperature of the snow layer (K)",
    "ecmwf_skin_reservoir_content": "ERA5 Skin reservoir content (kg m-2)",
    "ecmwf_volumetric_soil_water_layer_1": "ERA5 Volumetric soil water at level 1 (m3 m-3)",
    "ecmwf_volumetric_soil_water_layer_2": "ERA5 Volumetric soil water at level 2 (m3 m-3)",
    "ecmwf_volumetric_soil_water_layer_3": "ERA5 Volumetric soil water at level 3 (m3 m-3)",
    "ecmwf_volumetric_soil_water_layer_4": "ERA5 Volumetric soil water at level 4 (m3 m-3)",
    "ecmwf_forecast_albedo": "ERA5 Forecast albedo (dimensionless)",
    "ecmwf_surface_latent_heat_flux": "ERA5 Surface latent heat flux (W m-2)",
    "ecmwf_surface_net_solar_radiation": "ERA5 Surface net solar radiation (W m-2)",
    "ecmwf_surface_net_thermal_radiation": "ERA5 Surface net thermal radiation (W m-2)",
    "ecmwf_surface_sensible_heat_flux": "ERA5 Surface sensible heat flux (W m-2)",
    "ecmwf_surface_solar_radiation_downwards": "ERA5 Surface solar radiation downwards (W m-2)",
    "ecmwf_surface_thermal_radiation_downwards": "ERA5 Surface thermal radiation downwards (W m-2)",
    "ecmwf_evaporation_from_bare_soil": "ERA5 Evaporation from bare soil (m)",
    "ecmwf_evaporation_from_open_water_surfaces_excluding_oceans": "ERA5 Evaporation from open water surfaces excluding oceans (m)",
    "ecmwf_evaporation_from_the_top_of_canopy": "ERA5 Evaporation from the top of canopy (m)",
    "ecmwf_evaporation_from_vegetation_transpiration": "ERA5 Evaporation from vegetation transpiration (m)",
    "ecmwf_potential_evaporation": "ERA5 Potential evaporation (m)",
    "ecmwf_runoff": "ERA5 Runoff (m)",
    "ecmwf_snow_evaporation": "ERA5 Snow evaporation (m)",
    "ecmwf_sub_surface_runoff": "ERA5 Sub-surface runoff (m)",
    "ecmwf_surface_runoff": "ERA5 Surface runoff (m)",
    "ecmwf_total_evaporation": "ERA5 Total evaporation (m)",
    "ecmwf_10m_u_component_of_wind": "ERA5 Eastward component of wind at 10 meters (m s-1)",
    "ecmwf_10m_v_component_of_wind": "ERA5 Northward component of wind at 10 meters (m s-1)",
    "ecmwf_surface_pressure": "ERA5 Surface pressure (Pa)",
    "ecmwf_total_precipitation": "ERA5 Total precipitation (m)",
    "ecmwf_leaf_area_index_high_vegetation": "ERA5 Leaf area index for high vegetation (dimensionless)",
    "ecmwf_leaf_area_index_low_vegetation": "ERA5 Leaf area index for low vegetation (dimensionless)",
    "ecmwf_high_vegetation_cover": "ERA5 High vegetation cover (fraction)",
    "ecmwf_lake_cover": "ERA5 Lake cover (fraction)",
    "ecmwf_low_vegetation_cover": "ERA5 Low vegetation cover (fraction)",
    # "ecmwf_lake_total_depth": "ERA5 Lake total depth (m)",
    "sg_bdod": "Soilgrids Bulk density (cg/cm³) 0-30cm weighted mean",
    "sg_cec": "Soilgrids Cation exchange capacity at pH7 (mmol(c)/kg) 0-30cm weighted mean",
    "sg_cfvo": "Soilgrids Coarse fragments volumetric (cm³/dm³) 0-30cm weighted mean",
    "sg_clay": "Soilgrids Clay content (g/kg) 0-30cm weighted mean",
    "sg_nitrogen": "Soilgrids Nitrogen (cg/kg) 0-30cm weighted mean",
    "sg_phh2o": "Soilgrids pH in H₂O (pH×10) 0-30cm weighted mean",
    "sg_sand": "Soilgrids Sand content (g/kg) 0-30cm weighted mean",
    "sg_silt": "Soilgrids Silt content (g/kg) 0-30cm weighted mean",
    "sg_soc": "Soilgrids Soil organic carbon content (dg/kg) 0-30cm weighted mean",
    "sg_ocs": "Soilgrids Soil organic carbon stock (t/ha) 0-30cm weighted mean",
    "sg_ocd": "Soilgrids Organic carbon densities (hg/dm³) 0-30cm weighted mean",
}

QDA_OPTIONS = {
    "nx": 8,
    "nn": 0.001,
}

LCP_OPTIONS = {
    "delta": 1.0,
    "zeta": 2.0,
    "total": 30,
    "grid": 0.7,
}

ASD_OPTIONS = {
    "formulaf": "",  # AnGam~Week+Elev+Soil
    "formular": "",  # ~1|LCD
    "target": "H",
    "total": 15,
    "delta": 0.01,
    "resolution": 10,
}

ZSSA_OPTIONS = {
    "iterations": 100,
    "init": 20,
    "add": [10, 20, 30, 50],
    "from_glm": False,
}
